export const USER_SIGNED_UP = 'USER_SIGNED_UP';

export const RECEIVE_SESSION = 'RECEIVE_SESSION';
export const CLEAR_SESSION = 'CLEAR_SESSION';
export const USERNAME_CHANGED = 'USERNAME_CHANGED';
export const AVATAR_CHANGED = 'AVATAR_CHANGED';

export const RECEIVE_PROFILE = 'RECEIVE_PROFILE';
export const PASSWORD_CHANGED = 'PASSWORD_CHANGED';

export const RECEIVE_ERROR = 'RECEIVE_ERROR';
export const CLEAR_ERROR = 'CLEAR_ERROR';